In [7]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(
    "data/WPS-Index-2025-Data.csv",
    encoding="latin1"
)
df.head()

,WPS Index Rank,Country,Code,"Women, Peace, and Security Index",Region,Education,Employment,Financial Inclusion,Cell Phone Use,Parliamentary Representation,Absence of Legal Discrimination,Access to Justice,Maternal Mortality Ratio,Son Bias,Intimate partner violence,Community Safety,Political Violence Targeting Women,Proximity to Conflict
0,1,Denmark,DNK,0.939,DC,13.2,77.9,100.0,100.0,43.6,100.0,4.0,4.0,105.6,3.3,85.0,0.0,0.0
1,2,Iceland,ISL,0.932,DC,13.9,83.7,100.0,100.0,46.0,100.0,3.4,3.0,105.9,2.8,82.0,0.0,0.0
2,3,Norway,NOR,0.924,DC,13.1,78.6,100.0,100.0,44.4,96.9,3.7,1.0,106.1,4.4,86.0,0.0,0.0
3,3,Sweden,SWE,0.924,DC,12.8,82.2,100.0,100.0,45.0,100.0,3.7,4.0,105.6,6.3,74.0,0.0,0.0
4,5,Finland,FIN,0.921,DC,13.1,78.4,99.1,100.0,45.5,97.5,3.5,8.0,105.2,8.1,78.0,0.0,0.0

In [9]:
df.shape

(181, 18)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 18 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   WPS Index Rank                      181 non-null    int64
 1   Country                             181 non-null    object
 2   Code                                181 non-null    object
 3   Women, Peace, and Security Index    181 non-null    float64
 4   Region                              181 non-null    object
 5   Education                           181 non-null    float64
 6   Employment                          181 non-null    float64
 7   Financial Inclusion                 181 non-null    float64
 8   Cell Phone Use                      181 non-null    float64
 9   Parliamentary Representation        181 non-null    float64
 10  Absence of Legal Discrimination     181 non-null    float64
 11  Access to Justice                   181 non-null    float64
 12  Maternal Mortality Ratio            181 non-null    float64
 13  Son Bias                            181 non-null    float64
 14  Intimate partner violence           181 non-null    float64
 15  Community Safety                    181 non-null    float64
 16  Political Violence Targeting Women  181 non-null    float64
 17  Proximity to Conflict               181 non-null    float64
dtypes: float64(14), int64(1), object(3)
memory usage: 25.6+ KB

In [11]:
df.describe()

,WPS Index Rank,"Women, Peace, and Security Index",Education,Employment,Financial Inclusion,Cell Phone Use,Parliamentary Representation,Absence of Legal Discrimination,Access to Justice,Maternal Mortality Ratio,Son Bias,Intimate partner violence,Community Safety,Political Violence Targeting Women,Proximity to Conflict
count,181.000000,181.000000,181.000000,181.00000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000
mean,90.756906,0.683110,8.780110,60.30442,61.716022,84.903867,26.022652,78.256354,2.431492,119.171271,105.060773,11.605525,59.724862,0.108840,16.676243
std,52.426314,0.142989,3.573427,18.53927,27.718245,14.547999,12.128222,16.818215,0.841528,169.212542,1.643965,7.447003,16.416005,0.320814,29.663866
min,1.000000,0.279000,0.900000,5.50000,4.200000,28.000000,0.300000,26.300000,0.100000,1.000000,101.100000,1.700000,17.000000,0.000000,0.000000
25%,46.000000,0.590000,5.800000,51.60000,38.800000,77.400000,17.900000,70.600000,1.900000,11.000000,103.900000,5.900000,46.000000,0.000000,0.000000
50%,89.000000,0.685000,9.600000,62.30000,62.600000,90.000000,26.200000,81.300000,2.500000,47.000000,105.100000,9.100000,60.000000,0.000000,0.000000
75%,135.000000,0.797000,11.800000,75.80000,87.300000,95.000000,34.100000,90.600000,3.000000,155.000000,106.000000,16.700000,71.000000,0.100000,18.600000
max,181.000000,0.939000,14.000000,90.00000,100.000000,100.000000,61.300000,100.000000,4.000000,993.000000,111.300000,35.600000,97.000000,3.000000,100.000000